### ISSUE TITLE
"Create new note" leads to black screen

### ISSUE THREAD

**Issue by glow12121** [appml/nano#12]
Hi,

Recently i haven't been able to create new notes. As I tap on a cross, a blank black screen appears. If I switch to another window and back, I can again see the list of notes but a new note is not created.

I still can open and edit old notes.

I am on Android 11 (Lineage OS 18.1).

Kernel: 3.18.140-Redux-V2.06/93e2d093cc
#1 Fri Jan 21 05:24:36 UTC 2022

**Comment by appml** [comment]
Is the below setting enabled?
com.appmindlab.nano.pref_open_in_markdown

**Comment by glow12121** [comment]
I amended the settings file with the last line but to no changes. Tried closing and reopening Neutrinote as well.
```
com.appmindlab.nano.pref_auto_save|true
com.appmindlab.nano.pref_copy_attachments_to_repo|false
com.appmindlab.nano.pref_custom_filters|all;starred;A;B;C;D;E;F;G;H;I;J;K;L;M;N;O;P;Q;R;S;T;U;V;W;X;Y;Z
com.appmindlab.nano.pref_font_size|16
com.appmindlab.nano.pref_incremental_backup|false
com.appmindlab.nano.pref_lazy_update|false
com.appmindlab.nano.pref_location_aware|false
com.appmindlab.nano.pref_lux|false
com.appmindlab.nano.pref_margin|8
com.appmindlab.nano.pref_math_url|https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
com.appmindlab.nano.pref_order_by|modified
com.appmindlab.nano.pref_order_by_direction|DESC
com.appmindlab.nano.pref_show_hidden|false
com.appmindlab.nano.pref_theme|day
com.appmindlab.nano.pref_open_in_markdown|true
```

**Comment by appml** [comment]
Did you see the pencil icon on top right?

![Screenshot_20220926-092903](https://user-images.githubusercontent.com/7504229/192291538-bd61e9e1-800f-43f5-ace7-d5ef09502adf.png)

**Comment by glow12121** [comment]
> Did you see the pencil icon on top right?

After I tap on plus, a black screen appears with only the top status bar, nothing else. Status bar of Android, with the time, wifi status, etc, that is. I am not able to take a screenshot when this screen is on.

**Comment by appml** [comment]
Tried **com.appmindlab.nano.pref_open_in_markdown|false** ?  (be sure to Restore App Data after the change.)

**Comment by glow12121** [comment]
This didn't help either. What did help was deleting old files titled "New Note n". But thanks anyway!
