### ISSUE TITLE
Discover new files in the library folder and add them to note database

### ISSUE THREAD

**Issue by shaiay** [appml/nano#2]
When a new txt file appears in the library folder, add it to the notes database.
Use case:
I sync the note folder with syncthing to my PC
I add a new note from my PC using a  text editor
This note should appear in neurinote after syncthing syncs it to the phone

**Comment by appml** [comment]
By library folder, do you mean Local Repository?  

Do you have Syncthing running on your PC and phone?  New files should automatically be sync across to phone and picked up by neutriNote.
