### ISSUE TITLE
Open files with .md extension

### ISSUE THREAD

**Issue by MageJohn** [appml/nano#4]
neutriNote uses Markdown syntax, but saves it's files with the .txt extension. I would like to be able to sync notes from neutriNote to my computer and open them in a Markdown editor, but because of this limitation my editor won't recognize the files as being in Markdown syntax. Either neutriNote should use the .md extension by default, or there should be an option to use .md or any custom extension. 

EDIT: I've discovered that you can indeed export to a file with the .md extension. However that is a bit of a hassle, and I would like to be able to use the extension natively.

**Comment by appml** [comment]
To enable other file extensions, please apply these steps (also described in [Help](https://appml.github.io/nano/#hacks)):

1. Backup ALL app settings and notes.
2. Add a blank file called ~neutrinote_multitype.txt to your Local Repository.
3. Un-install neutriNote (or clear the app’s data under Android’s system settings).
4. Re-install neutriNote.
5. Once rescan finishes, file extensions will appear in note titles.
6. Restore app data.

**Comment by MageJohn** [comment]
Thanks, this works.

I have to ask however, why is this so complex and (seemingly) undocumented? I think many people would still benefit from a menu option.

**Comment by appml** [comment]
There are some "heavy duty" tasks behind the scene, such as database needs to be rebuilt and search index recreated.  So not merely a state change.

**Comment by ghost** [comment]
Hi,

I know that this is an older topic, but I struggle with a related problem. Just as @MageJohn, I'd very much prefer the .md extension (because I sync & edit the notes also on a PC).

I have successfully made the app show also the files of types other than .txt (using the procedure described above), but it brings a whole new (and rather critical) issue to the table: if one stores e.g. image files alongside the note files (for referencing them in the notes) and then accidentally opens any such non-text file from neutriNote with Auto Save enabled, this results in data corruption (the respective image file can no longer be opened). The same happens with PDFs or other non-text files.

Therefore: would you please consider making neutriNote open any file other than .txt and .md in the system default viewer? This would be excellent, because one would be able to open PDFs and other files directly from neutriNote, and no data corruption would occur.

An alternative (albeit less elegant) solution would be to make the preferred note file extension user-selectable (say, between .txt and .md). One would then only see the notes (files) with the preferred extension, while being able to sync and edit the notes comfortably on a PC.

Thank you.

nvx

**Comment by appml** [comment]
> 
> 
> Hi,
> 
> I know that this is an older topic, but I struggle with a related problem. Just as @MageJohn, I'd very much prefer the .md extension (because I sync & edit the notes also on a PC).
> 
> I have successfully made the app show also the files of types other than .txt (using the procedure described above), but it brings a whole new (and rather critical) issue to the table: if one stores e.g. image files alongside the note files (for referencing them in the notes) and then accidentally opens any such non-text file from neutriNote with Auto Save enabled, this results in data corruption (the respective image file can no longer be opened). The same happens with PDFs or other non-text files.
> 
> Therefore: would you please consider making neutriNote open any file other than .txt and .md in the system default viewer? This would be excellent, because one would be able to open PDFs and other files directly from neutriNote, and no data corruption would occur.
> 
> An alternative (albeit less elegant) solution would be to make the preferred note file extension user-selectable (say, between .txt and .md). One would then only see the notes (files) with the preferred extension, while being able to sync and edit the notes comfortably on a PC.
> 
> Thank you.
> 
> nvx

Hi, neutriNote does not write to any image file so it is highly improbable image files referred in-note will be affected.  The app per sec can already open any text based file (besides .txt and .md).  

Note however that file API (which neutriNote is built around) will be treated in a more restricted way in upcoming versions of Android.  You may notice a less universal text file open support across a variety of file centric apps.

**Comment by ghost** [comment]
Hi,

Thank you for your response. If I understand you correctly, neutriNote *should not* write to any non-text file even if:

* auto-save is enabled; AND
* files of other types are shown; AND
* one accidentally opens (as if it were a note) e.g. a non-binary PDF file without making any changes to the content.

What I experienced, however, was exactly the described behaviour -- anything "non-text" (extension not being txt, md, etc.), yet perhaps seeming to be a text file (such as a non-binary PDF as mentioned above) changed in size dramatically when I accidentally opened it in neutriNote and immediately returned back to the note list (e.g.: original PDF: 114 kB, modified PDF: 197 kB).

Well, I guess that it might be a good idea to put all those referenced files to a separate folder, which will make this entire issue more or less irrelevant...

Thanks for this great app! :)

nvx

**Comment by appml** [comment]
> 
> 
> Hi,
> 
> Thank you for your response. If I understand you correctly, neutriNote _should not_ write to any non-text file even if:
> 
>     * auto-save is enabled; AND
> 
>     * files of other types are shown; AND
> 
>     * one accidentally opens (as if it were a note) e.g. a non-binary PDF file without making any changes to the content.
> 
> 
> What I experienced, however, was exactly the described behaviour -- anything "non-text" (extension not being txt, md, etc.), yet perhaps seeming to be a text file (such as a non-binary PDF as mentioned above) changed in size dramatically when I accidentally opened it in neutriNote and immediately returned back to the note list (e.g.: original PDF: 114 kB, modified PDF: 197 kB).
> 
> Well, I guess that it might be a good idea to put all those referenced files to a separate folder, which will make this entire issue more or less irrelevant...
> 
> Thanks for this great app! :)
> 
> nvx

You might want to check with developer of the PDF viewer.  As mentioned, PDF is not a format natively supported by neutriNote.  No open / edit will be performed on the file type.   Best regard.
