### ISSUE TITLE
Download mathjax for offline use

### ISSUE THREAD

**Issue by sandorex** [appml/nano#5]
Should be simple enough, just download it from github and extract it somewhere
i'd do it, its an awesome app but i have no idea how it works, like how do you make such an app with 4 js files

**Comment by appml** [comment]
The app currently automatically keeps an offline cache upon first access to allow subsequent offline use.

Consider using Termux as well as it should offer other ways to keep the library (or any library) on device.  Just point to the url under localhost in neutriNote's settings.  Hope this helps.

**Comment by sandorex** [comment]
The cache did not work for me, i downloaded MathJax repo and pointed to it on the sd card and it works fine
