### ISSUE TITLE
Line break in Latex math

### ISSUE THREAD

**Issue by cdfa** [appml/nano#7]
Hi, I'm trying to add a line break in a Latex math segment, but it isn't working. Also tried `align` and `equation` blocks, but that didn't work either.

```
$$
  A = \frac{\pi r^2}{2} \\
   = \frac{1}{2} \pi r^2
$$
```

![Screenshot_20190908-172250__01](https://user-images.githubusercontent.com/8250462/64490479-66cccc80-d25d-11e9-98d4-668a8040398d.jpg)

**Comment by appml** [comment]
Due to conflict with other syntax supported by the app, please use 3 backslashes:

```
$$
  A = \frac{\pi r^2}{2} \\\
 = \frac{1}{2} \pi r^2
$$
```

**Comment by cdfa** [comment]
Ahh, that's a little odd, but no problem. Thanks!
