### ISSUE TITLE
Scrollbar for long notes

### ISSUE THREAD

**Issue by mocsa** [appml/nano#8]
If one has long notes spanning many pages, it is inconvenient to scroll with countless swipes.

Please implement a scrollbar on the side of the screen. There is already a position indicator which looks like a scrollbar but cannot be dragged. Please make it draggable (and also a bit thicker) so the text can be scrolled with it.

**Comment by appml** [comment]
In fact the note body itself is already implemented as an "enhanced" fast scrollbar.  To get to various parts of a note, it would be easier to conduct local search or take a look at how to add "table of contents" via Markdown under Help document.  Thanks.

**Comment by mocsa** [comment]
What do you mean by "the note body itself is already implemented as an "enhanced" fast scrollbar"? How can I use it? Is it documented somewhere? I searched for "scroll" at https://appml.github.io/nano/ and I found nothing about this.

**Comment by appml** [comment]
It has a scroll UI component on top and is enabled by default.   How big is your note?  A more general purpose way to go to different parts of contents remains to be local search.  Be sure to turn on **Lab Mode** for full function of local search.  HTH

**Comment by appml** [comment]
Closed as a new [tool](https://mastodon.social/@neutrinote/105154548852735829) is now available to address long note scrolling.
