### ISSUE TITLE
Markdown mode as default doesn't work

### ISSUE THREAD

**Issue by sk-Prime** [appml/nano#9]
I keep many notes in neutrinote to read them later. But it always open a note as editing mode. After googling i found that adding `open_in_markdown|true` at the setting_data file make preview/markdown mode as default. Unfortunately it doesn't work.

<img src="https://user-images.githubusercontent.com/26684644/95443752-c7f23280-097e-11eb-8fd3-fae8a2536967.png" width="300">
Tell me if the setting is wrong.

**Comment by appml** [comment]
Hi, did you do a "Restore App Data" after making the change? 
![Capture+_2020-10-08-07-08-16](https://user-images.githubusercontent.com/7504229/95450952-17ac0c00-0935-11eb-8e4a-0462d2a1ba01.png)

**Comment by sk-Prime** [comment]
Thanks, it worked. My unfortunate, i thought "**restore** app data" will do something terrible.

Do you have any plan on implementing password to access neutrinote?

**Comment by appml** [comment]
@sk-Prime Password protection has been under consideration for a while.  However, solutions like OpenKeychain are better due to open source and its transparency.   More info [here](https://mastodon.social/@neutrinote/101010578117781702).
